language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

install: pip install -e .[test]

script: nosetests --with-coverage --cover-package poff --cover-html --cover-branches

after_success:
    # Only deploy coverage from 2.7
    - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then ./travis/deploy_coverage.sh --verbose; fi


env:
  global:

    # GitHub access token that grants access to thusoys GitHub account
    - secure: "YPcb4zLaJEfqqNr3Q6TkqShT4x7Ba+sX2xFyhtQ+4gjeMiUp11n8YLAm5WlMtvWgd8Et80XhY/c7DR5v7NAJ5Za2rCfZw5rlWfc7hTFdl2EfpQJhGkllPZjH5RCyMUhX8Cg+HhtR+BRU5c1liLk76TLsXVGSuckLJON9hsa2WKQ="

notifications:
  email: false
