language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"

install: ./configure

script: ./test --with-coverage --cover-package poff --cover-html --cover-branches

after_success:
    # Only deploy coverage from 2.7
    - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then ./travis/deploy_coverage.sh --verbose; fi

env:
  global:

    # GitHub access token that grants access to thusoys GitHub account
    - secure: "gm6cGVMXR0h4T/6546Du+iQ53Iu9qnDINaXhnIc+EdM8tRfdkIO7aVvlvPbvZKxaIFzTRBDJTDBsTYQVagcTB5p47Px12iWOTMrlIYX/Bo62UgbPwzJ18MZ0VgLGprks92qnAZUdlxau/qmixbRjxpnVGtKMOwPBz1pgPOKmJlY="

notifications:
  email: false
